spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

logging:
  level:
    education.project: DEBUG

jwt:
  header: Authorization
  #HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
  #2024-szs-backend-engineer-employment-assignment-song-jun-sub-jwt-secret-key
  #https://www.base64encode.org/ko/
  secret: MjAyNC1zenMtYmFja2VuZC1lbmdpbmVlci1lbXBsb3ltZW50LWFzc2lnbm1lbnQtc29uZy1qdW4tc3ViLWp3dC1zZWNyZXQta2V5
  token-validity-in-seconds: 86400